### ISSUE TITLE
Hot swapping SD cards?

### ISSUE THREAD

**Issue by salocinx** [niklasekstrom/amiga-par-to-spi-adapter#1]
Hi. Thanks for sharing your great work! I have built an [sdbox](https://github.com/jbilander/sdbox) and also [proposed a fix](https://github.com/jbilander/sdbox/pull/7/commits/1a7851fff61c941c91e94ae2cb973d5a3e89b408) to avoid the Amiga hanging during boot if the adaptor is not plugged-in.

Do you have an idea how to implement hot swapping the SD cards? Would it be sufficient to [close](https://github.com/niklasekstrom/amiga-par-to-spi-adapter/blob/master/examples/spisd/device.c#L117) and [open](https://github.com/niklasekstrom/amiga-par-to-spi-adapter/blob/master/examples/spisd/device.c#L97) the device again after the SD card physically changed?

The eject and insertion events could be generated by the left and right outer pins of the SD card adaptor (using an input pin on the ATmega 328p).

**Comment by niklasekstrom** [comment]
Hi Nicolas!

Lets think. Like you say, there is a pin on the sd card connector, card detect (CD), that is either disconnected (when no card is in the connector) or connected to ground (when a card is inserted). There is a pin on the parallel port, ACK, that is connected to the FLG interrupt pin on 8520 CIAA. Unfortunately that interrupt pin can only trigger an interrupt when the flag pin goes from high to low, so the CD pin cannot be connected directly to the ACK pin (connecting CD to ACK would only allow detecting that the sd card is inserted, but not ejected). So the CD pin must be connected to some pin on the AVR, and another pin on the AVR connects to ACK. There are enough free pins on the AVR to do this, by using for example D2 and D3 (CD->D2, D3->ACK).

The AVR code must then be updated to poll the D2 pin to check for a change in CD, and propagate that change to ACK. The timing of the AVR code is a bit sensitive, but I think it should be possible to make it work.

In the Amiga driver there's a few changes that need to be made. The TD_CHANGESTATE, TD_CHANGENUM and TD_REMOVE commands should be implemented. TD_REMOVE is used by the file system to register a software interrupt that is triggered when a disk is inserted or removed. There must be some synchronization (between the FLG interrupt and the rest of the driver) so that eject/insert events can only occur between read and write commands.

The only "tricky" part of adding this feature (as far as I can see currently) is the modifications to the AVR code, since that code is heavily timing-dependent. However, as I wrote above, I think that should be doable. All the other changes  should be straight-forward.

There are a couple of additional things that might be of interest related to this:
- I didn't try to write the AVR code using interrupts, and right now I don't remember why. I assume I had some reason, but maybe I didn't think it through enough (or maybe I did, again, not sure). It might be worth to try to write the AVR code using interrupts and just see if that works out; it could make that code a bit simpler.
- If the sd card can be removed then I think that the MISO pin, which is an input on the AVR, should have a pull-up resistor so that the pin isn't floating (floating input pins should generally be avoided). I'm not sure if the internal pull-up resistor on PB4 (MISO) can be enabled while the SPI alternate pin function is enabled; I think it can be, but that should be verified, and if it can't then an external pull-up resistor should be used.

Lastly, nice job with the proposed fix to avoid the hanging during boot!

**Comment by salocinx** [comment]
Hi Niklas!

WOW! Your answer really knocked my socks off : ) ! I am highly motivated to implement your plan.

I am not programming MCUs professionally, but I will make some proposal and you can give your opinion. First I will try to make an interrupt based approach for the AVR code and see if it works out.

I am not yet familiar with the Amiga libraries, but there‘s nothing that can‘t be learned.

I will report back within the next few weeks.

Thanks again!

**Comment by niklasekstrom** [comment]
Cool :) Feel free to write if you have any questions!

There is an Amiga Discord server that I can recommend, the invite link is in the first post on [this page](https://eab.abime.net/showthread.php?t=85960). My username on that Discord is Niklas. If you want a faster/more interactive way to discuss you can write a private message there (and there are also several channels where people would be interested in this).

**Comment by salocinx** [comment]
Hi Niklas!

It's me again. I meanwhile did quite some research and learned many things about `SPI`, `ASM`, SW- and HW-interrupts and Amiga libraries. Everything quite new to me, but very intriguing! However, it seems that I have reached kind of a dead-end for my current abilities, so I need a little (or maybe a little more than little) help ;-p

I started with [jbilander sdbox](https://github.com/jbilander/sdbox/tree/master/sd) project and simplified the file structure and removed some unused files and code (there were duplicate code regarding `spi.h`). Additionally I added the `kprintf()` function to `common.h` and defined a macro named [SERIAL()](https://github.com/salocinx/amigasd/blob/3493f210d9761e04694f2ef26cb6406493fff0f3/amiga/source/common.h#L66) for this (with the help of jbilander - thanks). It lets me output debug information to the serial port of the Amiga which I then can monitor with a second Amiga using a null-moden serial cable.

In order to not mess up with either your or jbilanders project, I uploaded my modified code to a new repository. Once everything is working, I will start some pull-requests if desired. Here's the [link](https://github.com/salocinx/amigasd).

As you suggested, I started with the `AVR` code. Instead of re-writing the entire `AVR`, I just introduced a [pin-change interrupt](https://github.com/salocinx/amigasd/blob/3493f210d9761e04694f2ef26cb6406493fff0f3/avr/main.c#L78) on `PB0`. `PB0` is the `AVR` `GPIO` I am using to monitor the `CD'` signal of MicroSD card adaptor. I configured it to be [input-pullup](https://github.com/salocinx/amigasd/blob/3493f210d9761e04694f2ef26cb6406493fff0f3/avr/main.c#L65). First attempt was with a cable, which irreversibly damaged my SD card adaptor break-out board. Luckily I had a second one. I am now using a `1K2` resistor to connect `CD'` with the `AVR` (internal pull-up is `3K3` iirc, so this works fine). I then introduced the `ISR` in the [AVR code](https://github.com/salocinx/amigasd/blob/3493f210d9761e04694f2ef26cb6406493fff0f3/avr/main.c#L54) which currently inverts and propagates the `CD'` signal to the `ACK` pin of the Amiga Parallel port on `AVR`'s `PB1` pin.

Next I experimented with software- and hardware-interrupts on the Amiga. I hooked up a HW-interrupt to the `CIAA` for monitoring the `ACK` line (`FLG` interrupt) [here](https://github.com/salocinx/amigasd/blob/3493f210d9761e04694f2ef26cb6406493fff0f3/amiga/source/device.c#L99). This is where I am stuck. I tried to implement the `ISR` handler as `C` code as well as `ASM`. Phew, the word "baby-steps" really got a new meaning when it comes to `ASM`. I definitely need to read a book about this. My few `ASM` lines that should handle the `ACK/FLG` interrupt are in [disk-int.asm](https://github.com/salocinx/amigasd/blob/main/amiga/source/disk-int.asm) file and the `C` attempt is [here](https://github.com/salocinx/amigasd/blob/3493f210d9761e04694f2ef26cb6406493fff0f3/amiga/source/device.c#L86) in `device.c`.

As I understand, notifying Amiga OS about a disk-change should work something like this:

1.) After the device opens, I somewhen get a `TD_ADDCHANGEINT` command with a SW-interrupt stored in `io_Data`. I assign this interrupt to a [global field](https://github.com/salocinx/amigasd/blob/3493f210d9761e04694f2ef26cb6406493fff0f3/amiga/source/device.c#L257).
2.) I then get the `FLG` interrupt on `ACK` line and a trigger the SW-interrupt by calling `Cause(A1)`/`Cause(Interrupt*)` to notify Amiga OS.
3.) Amiga OS subsequently sends a `TD_CHANGENUM` command to check if a medium is inserted or not (certainly only if not crashed before).
4.) ... from here on I only can speculate how the procedure continues and if Amiga OS automatically removes the device from workbench etc.

Now when using my modified code, the following happens: The adaptor still works perfectly fine, mount/dismount and read/write all okay. The interrupt on `AVR` gets triggered when removing the SD card and the HW-interrupt on the Amiga's device driver also gets triggered fine. However, as soon as the SW-interrupt should be [Cause()'d](https://github.com/salocinx/amigasd/blob/3493f210d9761e04694f2ef26cb6406493fff0f3/amiga/source/device.c#L91), my Amiga crashes with blinking power LED and receiving a well-known red error message.

I probably miss some important precautions when using interrupts (and probably lots of other construction sites). Do you have some ideas?

PS.: I have some spare Plipbox and also MicroSD adaptor that I would send you for free if you like :) I lately checked-in to the suggested Discord with username `salocinx`, but I still need to get familiar to it. No hurry with answering...! I also can try to move my issues to Discord or any Amiga forum. I don't want to waste your time, you certainly have better things to do ; )

**Comment by niklasekstrom** [comment]
This is very interesting! So my time looking into this is definitively not wasted (at least not any more so than any of the other time I spend on this hobby 😄).

Let's discuss this on Discord since it's a bit more interactive/faster, and then we can write the conclusions here after we've figured it out, for completeness.

**Comment by niklasekstrom** [comment]
Hi Nicolas!

I finally got around to add support for hot swapping SD cards. I know you started looking at this before, but I was tempted to give it a go myself. Perhaps you can look at the code I ended up with and compare with your solution. Let me know if you have any questions!

**Comment by salocinx** [comment]
Hi Niklas

Wow, amazing - just amazing!!!

After we talked on Discord, I started to learn assembly and read a couple of old 80ties paperback books on the topic.
Then I also studied some AmigaOS code, namely trackdisk.device and some more. Very interesting, but also quite complex.
However, as I wanted to start to implement my new knowledge and start experimenting, I got a new freelance project which took all my energy away.

I am extremely looking forward to dive into your code and check how you solved the hot swap issue :-D !
But I have to be patient a little bit, I try to finish some milestone with my current freelance project and hope I can study your code by the end of the next week.

Thank you so much for notifying me!
